FROM node:alpine

USER node

RUN mkdir /home/node/src

WORKDIR /home/node/src

COPY --chown=node:node package.json ./
COPY --chown=node:node package-lock.json ./

RUN npm -v

RUN npm ci

COPY --chown=node:node . .

CMD ["npm", "start"]