version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /home/node/src/node_modules
      - .:/home/node/src/
  testing:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/src/node_modules
      - .:/home/node/src/
    command: ["npm", "run", "test"]